name       : gwyddion
version    : '2.63'
release    : 23
source     :
    - https://sourceforge.net/projects/gwyddion/files/gwyddion/2.63/gwyddion-2.63.tar.xz : 152b3f0db9ebd6c844c3f5b9d4385414f6fad6d33ed1ab5ceb0c58f351224dd3
homepage   : http://gwyddion.net/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Free SPM (AFM, SNOM/NSOM, STM, MFM, ...) data analysis software
description: |
    Gwyddion is a modular program for SPM (scanning probe microscopy) data visualization and analysis. Primarily is is intended for the analysis of height fields obtained by SPM techniques (AFM, MFM, STM, SNOM/NSOM) and it supports a lot of SPM data formats.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(cfitsio)
    - pkgconfig(fftw3)
    - pkgconfig(glu)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libzip)
    - pkgconfig(xmu)
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/OpenEXR-instead-of-ilmbase.patch
    %configure \
        --with-python=no \
        --enable-pygwy=no
build      : |
    %make
install    : |
    %make_install
    # Fix appstream generation
    mv $installdir/usr/share/applications/{gwyddion.desktop,net.gwyddion.Gwyddion.desktop}
