name       : gwyddion
version    : '2.60'
release    : 20
source     :
    - https://sourceforge.net/projects/gwyddion/files/gwyddion/2.60/gwyddion-2.60.tar.xz : dfc3c86ab7653b30eb54a5af57802242579c4d89b061e82dcd1c9aef5dc0bbf6
homepage   : http://gwyddion.net/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Free SPM (AFM, SNOM/NSOM, STM, MFM, ...) data analysis software
description: |
    Gwyddion is a modular program for SPM (scanning probe microscopy) data visualization and analysis. Primarily is is intended for the analysis of height fields obtained by SPM techniques (AFM, MFM, STM, SNOM/NSOM) and it supports a lot of SPM data formats.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(cfitsio)
    - pkgconfig(fftw3)
    - pkgconfig(glu)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(gtksourceview-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libzip)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(xmu)
    - bzip2-devel
rundeps    :
    - python-gtk2
setup      : |
    %patch -p1 < $pkgfiles/OpenEXR-instead-of-ilmbase.patch
    %configure
build      : |
    %make
install    : |
    %make_install
