name       : gwyddion
version    : 2.48
release    : 4
source     :
    - https://freefr.dl.sourceforge.net/project/gwyddion/gwyddion/2.48/gwyddion-2.48.tar.xz : 9d3fa861bad2b3df43383e2ca3deacf5111bf2a9484ba31523960ba650e13185
license    : GPL-2.0
component  : office.scientific
summary    : Free SPM (AFM, SNOM/NSOM, STM, MFM, ...) data analysis software
description: |
    Gwyddion is a modular program for SPM (scanning probe microsopy) data visualization and analysis. Primarily is is intended for the analysis of height fields obtained by SPM techniques (AFM, MFM, STM, SNOM/NSOM) and it supports a lot of SPM data formats.
builddeps  :
    - pkgconfig(cfitsio)
    - pkgconfig(fftw3)
    - pkgconfig(glu)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(gtksourceview-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libwebp)
    - pkgconfig(libzip)
    - pkgconfig(OpenEXR)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(unique-3.0)
    - pkgconfig(xmu)
rundeps    :
    - python-gtk2
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
